cuda_base_url: "http://127.0.0.1:2224/"
client_config:
  mw:
    exclude_bounds: [ ]
    npc_threshold: 0.9995
    npc_nms: 0.4
    target_rect: []
    target_name_rect: []
    player_rects: []
    web:
      port: ":2223"
    macros_base_url: "http://192.168.1.73:8088/"
