package internal

var (
	NpcList = map[string]any{
		"Bearded Keltir":                  nil,
		"Block":                           nil,
		"Elpy":                            nil,
		"Gremlin":                         nil,
		"Gremlin Scavenger":               nil,
		"Grey Elpy":                       nil,
		"Rabbit":                          nil,
		"Young Brown Fox":                 nil,
		"Young Brown Keltir":              nil,
		"Young Crimson Fox":               nil,
		"Young Fox":                       nil,
		"Young Grey Keltir":               nil,
		"Young Keltir":                    nil,
		"Young Prairie Keltir":            nil,
		"Young Red Fox":                   nil,
		"Young Red Keltir":                nil,
		"Brown Fox":                       nil,
		"Brown Keltir":                    nil,
		"Fox":                             nil,
		"Grey Keltir":                     nil,
		"Longtail Fox":                    nil,
		"Longtail Keltir":                 nil,
		"Prairie Fox":                     nil,
		"Prairie Keltir":                  nil,
		"Red Fox":                         nil,
		"Red Keltir":                      nil,
		"Bonaparterius":                   nil,
		"Dominant Grey Keltir":            nil,
		"Elder Brown Fox":                 nil,
		"Elder Brown Keltir":              nil,
		"Elder Fox":                       nil,
		"Elder Keltir":                    nil,
		"Elder Longtail Fox":              nil,
		"Elder Longtail Keltir":           nil,
		"Elder Prairie Fox":               nil,
		"Elder Prairie Keltir":            nil,
		"Elder Red Fox":                   nil,
		"Elder Red Keltir":                nil,
		"Ramsebalius":                     nil,
		"Ashen Wolf":                      nil,
		"Black Wolf":                      nil,
		"Gray Wolf":                       nil,
		"Great Snow Wolf":                 nil,
		"Kasha Wolf":                      nil,
		"Kobold":                          nil,
		"Murtika's Warhound":              nil,
		"Roko's Warhound":                 nil,
		"Tanukia's Warhound":              nil,
		"Wolf":                            nil,
		"Dominant Black Wolf":             nil,
		"Elder Wolf":                      nil,
		"Giant Toad":                      nil,
		"Goblin":                          nil,
		"Goblin Grave Robber":             nil,
		"Goblin Raider":                   nil,
		"Goblin Snooper":                  nil,
		"Black Timber Wolf":               nil,
		"Green Goblin":                    nil,
		"Imp":                             nil,
		"Kaboo Orc":                       nil,
		"Kasha Timber Wolf":               nil,
		"Orc":                             nil,
		"Rakeclaw Imp":                    nil,
		"Utuku Orc":                       nil,
		"Zombie":                          nil,
		"Imp Elder":                       nil,
		"Kaboo Orc Grunt":                 nil,
		"Mountain Werewolf":               nil,
		"Orc Grunt":                       nil,
		"Rakeclaw Imp Hunter":             nil,
		"Utuku Orc Grunt":                 nil,
		"Balor Orc Archer":                nil,
		"Goblin Brigand":                  nil,
		"Goblin Lookout":                  nil,
		"Goblin Scout":                    nil,
		"Green Dryad":                     nil,
		"Kaboo Orc Archer":                nil,
		"Mountain Fungus":                 nil,
		"Muertos Archer":                  nil,
		"Murtika":                         nil,
		"Orc Archer":                      nil,
		"Roko":                            nil,
		"Tanukia":                         nil,
		"Utuku Orc Archer":                nil,
		"Walking Fungus":                  nil,
		"Garum Werewolf":                  nil,
		"Green Fungus":                    nil,
		"Maraku Werewolf":                 nil,
		"Relic Werewolf":                  nil,
		"Spirit Of Mirrors":               nil,
		"Spore Fungus":                    nil,
		"Werewolf":                        nil,
		"Balor Orc Fighter":               nil,
		"Baraq Orc Fighter":               nil,
		"Blade Bat":                       nil,
		"Evil Eye":                        nil,
		"Evil Eye Watcher":                nil,
		"Goblin Brigand Lieutenant":       nil,
		"Goblin Thief":                    nil,
		"Kaboo Orc Fighter":               nil,
		"Monster Eye":                     nil,
		"Monster Eye Tracker":             nil,
		"Mountain Werewolf Chief":         nil,
		"Orc Fighter":                     nil,
		"Orc Marksman":                    nil,
		"Orc Sniper":                      nil,
		"Orc Warrior":                     nil,
		"Pirate Captain Uthanka":          nil,
		"Rakeclaw Imp Chieftain":          nil,
		"Sylph":                           nil,
		"Tunath Orc Marksman":             nil,
		"Vaiss Orc":                       nil,
		"Vampire Bat":                     nil,
		"Varikan Brigand Leader":          nil,
		"Werewolf Hunter":                 nil,
		"White Fang":                      nil,
		"Balor Orc Lieutenant":            nil,
		"Baraq Orc Warrior Leader":        nil,
		"Batoh":                           nil,
		"Bhato Bloodspear":                nil,
		"Darkwing Bat":                    nil,
		"Drill Bat":                       nil,
		"Kaboo Orc Fighter Lieutenant":    nil,
		"Kamut":                           nil,
		"Kraacul Blackskull":              nil,
		"Kracha":                          nil,
		"Lizardman":                       nil,
		"Magical Weaver":                  nil,
		"Mineshaft Bat":                   nil,
		"Muertos Guard":                   nil,
		"Orc Lieutenant":                  nil,
		"Orc Warrior Leader":              nil,
		"Taarq Blackskull":                nil,
		"Tanuki Skullcrusher":             nil,
		"Tumran Orc Brigand":              nil,
		"Turel":                           nil,
		"Uoph":                            nil,
		"Vaiss Orc Warrior Leader":        nil,
		"Varangka's Tracker":              nil,
		"Akaste Bone Soldier":             nil,
		"Balor Orc Fighter Leader":        nil,
		"Baranka's Messenger":             nil,
		"Barbed Bat":                      nil,
		"Blood Fungus":                    nil,
		"Dungeon Skeleton":                nil,
		"Gemstone Beast":                  nil,
		"Goblin Servant":                  nil,
		"Goblin Tomb Raider Leader":       nil,
		"Gremlin Filcher":                 nil,
		"Grizzly":                         nil,
		"Kaboo Orc Fighter Leader":        nil,
		"Lizardman Scout":                 nil,
		"Muertos Scout":                   nil,
		"Orc Escort":                      nil,
		"Orc Fighter Leader":              nil,
		"Puma":                            nil,
		"Skeleton":                        nil,
		"Skeleton Hunter":                 nil,
		"Slave Skeleton":                  nil,
		"Tunath Orc Warrior":              nil,
		"Werewolf Chieftain":              nil,
		"Calpico":                         nil,
		"Cave Bat":                        nil,
		"Colossus":                        nil,
		"Darkstone Golem":                 nil,
		"Dryad":                           nil,
		"Dungeon Skeleton Archer":         nil,
		"Festering Bat":                   nil,
		"Goblin Lord":                     nil,
		"Grave Keeper":                    nil,
		"Greystone Golem":                 nil,
		"Kobold Looter Bepook":            nil,
		"Lizardman Warrior":               nil,
		"Marsh Zombie":                    nil,
		"Skeleton Archer":                 nil,
		"Skeleton Hunter Archer":          nil,
		"Stone Giant":                     nil,
		"Stone Golem":                     nil,
		"Akaste Bone Archer":              nil,
		"Carnivorous Fungus":              nil,
		"Crasher":                         nil,
		"Doom Soldier":                    nil,
		"Dread Soldier":                   nil,
		"Dryad Elder":                     nil,
		"Evil Eye Lookout":                nil,
		"Evil Eye Patroller":              nil,
		"Felim Lizardman":                 nil,
		"Goblin Brigand Leader":           nil,
		"Hunter Bear":                     nil,
		"Maraku Werewolf Chieftain":       nil,
		"Marsh Zombie Lord":               nil,
		"Misery Skeleton":                 nil,
		"Muertos Warrior":                 nil,
		"Orc Champion":                    nil,
		"Plague Zombie":                   nil,
		"Red Bear":                        nil,
		"Skeleton Marksman":               nil,
		"Skeleton Sentinel":               nil,
		"Stone Soldier":                   nil,
		"Vuku Orc":                        nil,
		"Whinstone Golem":                 nil,
		"Cat's Eye Bandit":                nil,
		"Cave Spider":                     nil,
		"Crimson Spider":                  nil,
		"Crimson Tarantula":               nil,
		"Crypt Horror":                    nil,
		"Dungeon Spider":                  nil,
		"Felim Lizardman Scout":           nil,
		"Giant Spider":                    nil,
		"Grotto Golem":                    nil,
		"Herb Jar":                        nil,
		"Kasha Bear":                      nil,
		"Kasha Spider":                    nil,
		"Langk Lizardman":                 nil,
		"Lesser Dark Horror":              nil,
		"Mist Terror":                     nil,
		"Muertos Captain":                 nil,
		"Obsidian Golem":                  nil,
		"Opal Beast":                      nil,
		"Quicksilver Beast":               nil,
		"Redeye Bat":                      nil,
		"Ruin Zombie":                     nil,
		"Scavenger Spider":                nil,
		"Shadow Beast":                    nil,
		"Shady Muertos":                   nil,
		"Shield Skeleton":                 nil,
		"Skeleton Lord":                   nil,
		"Spartoi":                         nil,
		"Twink Puma":                      nil,
		"Vrykolakas":                      nil,
		"Vuku Orc Archer":                 nil,
		"Will-O-Wisp":                     nil,
		"Boogle Ratman":                   nil,
		"Brown Bear":                      nil,
		"Cave Fang Spider":                nil,
		"Dark Horror":                     nil,
		"Dark Terror":                     nil,
		"Giant Bee":                       nil,
		"Gora Werewolf":                   nil,
		"Grotto Leopard":                  nil,
		"Hook Spider":                     nil,
		"Hunter Tarantula":                nil,
		"Kasha Fang Spider":               nil,
		"Kuruka Ratman":                   nil,
		"Langk Lizardman Scout":           nil,
		"Pincher":                         nil,
		"Ratman Spy":                      nil,
		"Red Scavenger Spider":            nil,
		"Ruin Zombie Leader":              nil,
		"Shady Muertos Guard":             nil,
		"Silent Horror":                   nil,
		"Skeleton Infantryman":            nil,
		"Stone Guardian":                  nil,
		"Talon Spider":                    nil,
		"Wererat":                         nil,
		"Akaste Bone Warlord":             nil,
		"Blade Spider":                    nil,
		"Bugbear Raider":                  nil,
		"Cave Blade Spider":               nil,
		"Corpse Candle":                   nil,
		"Felim Lizardman Warrior":         nil,
		"Grizzly Bear":                    nil,
		"Grotto Grizzly":                  nil,
		"Honey Bear":                      nil,
		"Kasha Bear Totem Spirit":         nil,
		"Kasha Blade Spider":              nil,
		"Kuruka Ratman Hunter":            nil,
		"Langk Lizardman Warrior":         nil,
		"Moonstone Beast":                 nil,
		"Muertos Lieutenant":              nil,
		"Ol Mahum Novice":                 nil,
		"Ol Mahum Sentry":                 nil,
		"Omen Beast":                      nil,
		"Orc Shaman":                      nil,
		"Ore Bat":                         nil,
		"Phantom Salamander":              nil,
		"Pincer Spider":                   nil,
		"Pinrul":                          nil,
		"Plunder Tarantula":               nil,
		"Prowler":                         nil,
		"Ruin Imp":                        nil,
		"Salamander":                      nil,
		"Scarlet Salamander":              nil,
		"Shade Horror":                    nil,
		"Shady Muertos Captain":           nil,
		"Tracker Skeleton":                nil,
		"Undead Priest":                   nil,
		"Undine":                          nil,
		"Vuku Orc Fighter":                nil,
		"Water Seer":                      nil,
		"Wererat Leader":                  nil,
		"Black Leopard":                   nil,
		"Boogle Ratman Leader":            nil,
		"Crystalline Beast":               nil,
		"Durka Spirit":                    nil,
		"Evil Eye Seer":                   nil,
		"Kuruka Ratman Leader":            nil,
		"Lirein":                          nil,
		"Mana Seeker":                     nil,
		"Muertos Commander":               nil,
		"Ratman Hunter":                   nil,
		"Red Eye Barbed Bat":              nil,
		"Salamander Elder":                nil,
		"Scarlet Salamander Elder":        nil,
		"Scavenger Bat":                   nil,
		"Scavenger Wererat":               nil,
		"Shady Muertos Archer":            nil,
		"Shady Muertos Warrior":           nil,
		"Succubus Handmaiden":             nil,
		"Sukar Wererat":                   nil,
		"Tainted Zombie":                  nil,
		"Tracker Skeleton Leader":         nil,
		"Undine Elder":                    nil,
		"Venomous Spider":                 nil,
		"Akaste Bone Lord":                nil,
		"Arachnid Tracker":                nil,
		"Garden Guard":                    nil,
		"Kasha Imp":                       nil,
		"Langk Lizardman Sentinel":        nil,
		"Lirein Elder":                    nil,
		"Northern Trimden":                nil,
		"Pitchstone Golem":                nil,
		"Ratman Sub Chieftain":            nil,
		"Ratman Warrior":                  nil,
		"Salamander Noble":                nil,
		"Shady Muertos Commander":         nil,
		"Shady Muertos Wizard":            nil,
		"Skeleton Longbowman":             nil,
		"Skeleton Scout":                  nil,
		"Stink Zombie":                    nil,
		"Sukar Wererat Leader":            nil,
		"Tamil":                           nil,
		"Undead Slave":                    nil,
		"Undine Noble":                    nil,
		"Zombie Soldier":                  nil,
		"Akaste Succubus":                 nil,
		"Arachnid Predator":               nil,
		"Baar Dre Vanil":                  nil,
		"Barrow Guardian":                 nil,
		"Bruin Lizardman":                 nil,
		"Bumbum":                          nil,
		"Chewba":                          nil,
		"Chuchu":                          nil,
		"Dark Succubus":                   nil,
		"Dion Grizzly":                    nil,
		"Dre Vanil":                       nil,
		"Dre Vanil Tracker":               nil,
		"Dwarf Ghost":                     nil,
		"Elf Ghost":                       nil,
		"Enku Orc Shaman":                 nil,
		"Ghost":                           nil,
		"Griffon":                         nil,
		"Hallowed Watchman":               nil,
		"Heitafu":                         nil,
		"Human Ghost":                     nil,
		"Kerope Werewolf":                 nil,
		"Lesser Succubus":                 nil,
		"Lycanthrope":                     nil,
		"Maille Lizardman":                nil,
		"Mandragora Sprout":               nil,
		"Minsku":                          nil,
		"Ol Mahum Officer Tak":            nil,
		"Picubo":                          nil,
		"Ratman Chieftain":                nil,
		"Ruin Bat":                        nil,
		"Sacrifice Of The Sacrificed":     nil,
		"Skeleton Bowman":                 nil,
		"Sumi":                            nil,
		"Timora Orc":                      nil,
		"Umbar Orc":                       nil,
		"Varool Foulclaw":                 nil,
		"Virud Lizardman":                 nil,
		"Wanuk":                           nil,
		"Zakan":                           nil,
		"Akaste Succubus Turen":           nil,
		"Baranka's Escort":                nil,
		"Bugbear":                         nil,
		"Dre Vanil Beholder":              nil,
		"Enku Orc Champion":               nil,
		"Ghost Guardian":                  nil,
		"Giant Poison Bee":                nil,
		"Gigant Slave":                    nil,
		"Hobgoblin":                       nil,
		"Lesser Succubus Turen":           nil,
		"Lith Scout":                      nil,
		"Nightmare Weaver":                nil,
		"Northern Goblin":                 nil,
		"Ol Mahum Patrol":                 nil,
		"Ol Mahum Recruit":                nil,
		"Relic Spartoi":                   nil,
		"Ruin Imp Elder":                  nil,
		"Ruin Spartoi":                    nil,
		"Virud Lizardman Scout":           nil,
		"Wandering Eye":                   nil,
		"Akaste Succubus Tilfo":           nil,
		"Arviterre's Guardian":            nil,
		"Baranka's Guard":                 nil,
		"Barrow Seer":                     nil,
		"Cloudy Beast":                    nil,
		"Dre Vanil Disposer":              nil,
		"Dre Vanil Slayer":                nil,
		"Guardian of Observation":         nil,
		"Guardian of Prediction":          nil,
		"Guardian of Records":             nil,
		"Guardian of Secrets":             nil,
		"Hallowed Seer":                   nil,
		"Harkilgamed's Gatekeeper":        nil,
		"Hungry Eye":                      nil,
		"Kamael Guard":                    nil,
		"Kasha Imp Turen":                 nil,
		"Katenar's Gatekeeper":            nil,
		"Kirunak":                         nil,
		"Langk Lizardman Lieutenant":      nil,
		"Lesser Succubus Tilfo":           nil,
		"Maille Lizardman Scout":          nil,
		"Merkenis":                        nil,
		"Monster Eye Searcher":            nil,
		"Mystical Weaver":                 nil,
		"Nerkas":                          nil,
		"Ol Mahum Guard":                  nil,
		"Ol Mahum Ranger":                 nil,
		"Raging Spartoi":                  nil,
		"Red Eye Vampire Bat":             nil,
		"Rodenpicula's Gatekeeper":        nil,
		"Spicula's Guard":                 nil,
		"Spine Golem":                     nil,
		"Virud Lizardman Warrior":         nil,
		"Zombie Warrior":                  nil,
		"Bloody Bee":                      nil,
		"Catacomb Barbed Bat":             nil,
		"Kasha Dire Wolf":                 nil,
		"Kerope Werewolf Chief":           nil,
		"Mandragora Sapling":              nil,
		"Ol Mahum":                        nil,
		"Ol Mahum Deserter":               nil,
		"Ol Mahum Reserve":                nil,
		"Ol Mahum Straggler":              nil,
		"Ol Mahum Supplier":               nil,
		"Tomlan Kamos":                    nil,
		"Tumran Bugbear":                  nil,
		"Underground Werewolf":            nil,
		"Veelan Bugbear":                  nil,
		"Virud Lizardman Shaman":          nil,
		"Young Araneid":                   nil,
		"Dire Wolf":                       nil,
		"Giant Araneid":                   nil,
		"Giant Leech":                     nil,
		"Gigant Acolyte":                  nil,
		"Kasha Bugbear":                   nil,
		"Langk Lizardman Shaman":          nil,
		"Lith Witch":                      nil,
		"Maille Lizardman Guard":          nil,
		"Northern Goblin Leader":          nil,
		"Ol Mahum Officer":                nil,
		"Ol Mahum Shooter":                nil,
		"Plain Grizzly":                   nil,
		"Tumran Bugbear Warrior":          nil,
		"Turek War Hound":                 nil,
		"Underground Kobold":              nil,
		"Veelan Bugbear Warrior":          nil,
		"Virud Lizardman Matriarch":       nil,
		"Baar Dre Vanil Destroyer":        nil,
		"Cloudy Beast Turen":              nil,
		"Dead Pit Skeleton Archer":        nil,
		"Enchanted Spine Golem":           nil,
		"Giant Mist Leech":                nil,
		"Grave Guardian":                  nil,
		"Grim Wolf":                       nil,
		"Howler":                          nil,
		"Kadif Werewolf":                  nil,
		"Langk Lizardman Leader":          nil,
		"Malcom":                          nil,
		"Mandragora Blossom":              nil,
		"Monster Eye Gazer":               nil,
		"Monster Eye Watcher":             nil,
		"Ol Mahum Archer":                 nil,
		"Ol Mahum Captain":                nil,
		"Ol Mahum Patrolman":              nil,
		"Poison Araneid":                  nil,
		"Turek Orc Sentinel":              nil,
		"Vault Guardian":                  nil,
		"White Skull Kanabion":            nil,
		"Catacomb Wisp":                   nil,
		"Dead Pit Spartoi":                nil,
		"Follower of Ariosh":              nil,
		"Gray Ant":                        nil,
		"Grim Grizzly":                    nil,
		"Maille Lizardman Warrior":        nil,
		"Monster Eye Destroyer":           nil,
		"Ol Ariosh":                       nil,
		"Ol Mahum General":                nil,
		"Ol Mahum Guerilla":               nil,
		"Ol Mahum Support Troop":          nil,
		"Ranc Deumus":                     nil,
		"Selu Lizardman Scout":            nil,
		"Skeleton Royal Guard":            nil,
		"Sobbing Wind":                    nil,
		"Specter":                         nil,
		"Turek Orc Footman":               nil,
		"Babbling Wind":                   nil,
		"Gargoyle":                        nil,
		"Gigant Overseer":                 nil,
		"Glass Jaguar":                    nil,
		"Grave Robber Lookout":            nil,
		"Grave Robber Scout":              nil,
		"Grave Seer":                      nil,
		"Horror Mist Ripper":              nil,
		"King of the Araneid":             nil,
		"Kuran Kobold":                    nil,
		"Lafi Lizardman":                  nil,
		"Lesser Basilisk":                 nil,
		"Lith Warrior":                    nil,
		"Ol Mahum Raider":                 nil,
		"Picot Araneid":                   nil,
		"Selu Lizardman Warrior":          nil,
		"Skeleton Pikeman":                nil,
		"Sorrow Maiden":                   nil,
		"Turek Orc Archer":                nil,
		"Turek Orc Supplier":              nil,
		"Underground Kobold Warrior":      nil,
		"Vault Seer":                      nil,
		"Basilisk":                        nil,
		"Catacomb Serpent":                nil,
		"Claw Of Succubus":                nil,
		"Dead Pit Horror":                 nil,
		"Delu Lizardman":                  nil,
		"Delu Lizardman Headhunter":       nil,
		"Giant Crimson Ant":               nil,
		"Giggling Wind":                   nil,
		"Grave Robber Ranger":             nil,
		"Kuran Kobold Warrior":            nil,
		"Lafi Lizardman Scout":            nil,
		"Maille Lizardman Shaman":         nil,
		"Neer Crawler":                    nil,
		"Ol Mahum Legionnaire":            nil,
		"Ol Mahum Marksman":               nil,
		"Skeleton Axeman":                 nil,
		"Turek Orc Skirmisher":            nil,
		"Androscorpio":                    nil,
		"Ant Larva":                       nil,
		"Delu Lizardman Scout":            nil,
		"Ghost of a Soldier":              nil,
		"Grave Keeper Spartoi":            nil,
		"Grave Robber Guard":              nil,
		"Iron Ore Golem":                  nil,
		"Lost Beholder":                   nil,
		"Lost Watcher":                    nil,
		"Marsh Stakato":                   nil,
		"Neer Ghoul Berserker":            nil,
		"Ol Mahum Champion":               nil,
		"Ol Mahum Commander":              nil,
		"Ol Mahum Sergeant":               nil,
		"Patin Archer":                    nil,
		"Ritmal Swordsman":                nil,
		"Singing Wind":                    nil,
		"Skeleton Marauder":               nil,
		"Turek Orc Shaman":                nil,
		"Amber Basilisk":                  nil,
		"Androscorpio Hunter":             nil,
		"Ant":                             nil,
		"Arachnid Hunter":                 nil,
		"Bandit Sweeper":                  nil,
		"Barrow Sentinel":                 nil,
		"Begrudged Kanabion":              nil,
		"Black Willow":                    nil,
		"Delu Lizardman Warrior":          nil,
		"Gigant Footman":                  nil,
		"Grave Robber Fighter":            nil,
		"Greedy Geist":                    nil,
		"Hallowed Sentinel":               nil,
		"Hatu Weird Bee":                  nil,
		"Lith Guard":                      nil,
		"Maille Lizardman Matriarch":      nil,
		"Ol Mahum Van Grunt":              nil,
		"Rakin Salamander":                nil,
		"Rakin Undine":                    nil,
		"Silenos":                         nil,
		"Skeleton Raider":                 nil,
		"Stinger Wasp":                    nil,
		"Talakin":                         nil,
		"Turek Orc Warlord":               nil,
		"Unicorn Of Eva":                  nil,
		"Watchman of the Plains":          nil,
		"Whispering Wind":                 nil,
		"Ant Captain":                     nil,
		"Bandit Hound":                    nil,
		"Batur Orc":                       nil,
		"Breka Orc":                       nil,
		"Catacomb Scavenger Bat":          nil,
		"Ghost of a Loyal Vassal":         nil,
		"Magical Eye":                     nil,
		"Marsh Stakato Worker":            nil,
		"Roughly Hewn Rock Golem":         nil,
		"Sentinel Of Water":               nil,
		"Strain":                          nil,
		"Turak Bugbear":                   nil,
		"Ant Overseer":                    nil,
		"Bandit Watchman":                 nil,
		"Barrow Monk":                     nil,
		"Batur Orc Archer":                nil,
		"Breka Orc Archer":                nil,
		"Death Fire":                      nil,
		"Delu Lizardman Supplier":         nil,
		"Dre Vanil Warrior":               nil,
		"Ghost of a General":              nil,
		"Ghoul":                           nil,
		"Hallowed Monk":                   nil,
		"Harpy":                           nil,
		"Hatu Dire Wolf":                  nil,
		"Kanil Succubus":                  nil,
		"King Bugbear":                    nil,
		"Male Ant":                        nil,
		"Ol Mahum Van Archer":             nil,
		"Roxide":                          nil,
		"Skeleton Knight":                 nil,
		"Succubus":                        nil,
		"Tatoma":                          nil,
		"Toad Lord":                       nil,
		"Ant Recruit":                     nil,
		"Batur Orc Warrior":               nil,
		"Breka Orc Warrior":               nil,
		"Crimson Hatu Otis":               nil,
		"Delu Lizardman Special Agent":    nil,
		"Enku Orc Overlord":               nil,
		"Ghost of a Batur Chief":          nil,
		"Ghost of a Morek Chief":          nil,
		"Ghost of a Turka Chief":          nil,
		"Gigant Cleric":                   nil,
		"Granite Golem":                   nil,
		"Lesser Warlike Tyrant":           nil,
		"Lith Medium":                     nil,
		"Marsh Stakato Soldier":           nil,
		"Neer Bodyguard":                  nil,
		"Rowin Undine":                    nil,
		"Salamander Rowin":                nil,
		"Snow Lynx":                       nil,
		"Spirit of Water":                 nil,
		"Troll":                           nil,
		"Turak Bugbear Warrior":           nil,
		"Ant Patrol":                      nil,
		"Bandit Undertaker":               nil,
		"Batur Orc Shaman":                nil,
		"Bloody Axe Turmak":               nil,
		"Breka Orc Shaman":                nil,
		"Catacomb Shadow":                 nil,
		"Cursed Seer":                     nil,
		"Dead Seeker":                     nil,
		"Harpy Matriarch":                 nil,
		"Hatu Brown Bear":                 nil,
		"Marsh Spider":                    nil,
		"Medusa":                          nil,
		"Ol Mahum Lord":                   nil,
		"Ol Mahum Van Leader":             nil,
		"Puncher":                         nil,
		"Succubus Queen":                  nil,
		"Turek Orc Elder":                 nil,
		"Ant Guard":                       nil,
		"Ant Soldier":                     nil,
		"Bandit Assassin":                 nil,
		"Batur Orc Overlord":              nil,
		"Bloody Axe Elite":                nil,
		"Breka Orc Overlord":              nil,
		"Cruma Marshlands Traitor":        nil,
		"Delu Lizardman Commander":        nil,
		"Delu Lizardman Shaman":           nil,
		"Dread Wolf":                      nil,
		"Field Stalker":                   nil,
		"Gigantiops":                      nil,
		"Grave Sentinel":                  nil,
		"Guardian Angel":                  nil,
		"Hangman Tree":                    nil,
		"Lava Salamander":                 nil,
		"Leto Lizardman":                  nil,
		"Leto Lizardman Agent":            nil,
		"Marsh Stakato Drone":             nil,
		"Marsh Stakato Marquess":          nil,
		"Nahir":                           nil,
		"Nurse Ant":                       nil,
		"Rakul":                           nil,
		"Rotten Kanabion":                 nil,
		"Spirit of Sir Herod":             nil,
		"Two-Headed Giant":                nil,
		"Tyrant":                          nil,
		"Vault Sentinel":                  nil,
		"Warlike Tyrant":                  nil,
		"Wasp Worker":                     nil,
		"Wyrm":                            nil,
		"Ant Warrior Captain":             nil,
		"Bandit Warrior":                  nil,
		"Baraham":                         nil,
		"Bloom":                           nil,
		"Breka Overlord Haka":             nil,
		"Breka Overlord Jaka":             nil,
		"Breka Overlord Marka":            nil,
		"Cave Ant Larva":                  nil,
		"Crimson Werewolf":                nil,
		"Crokian":                         nil,
		"Delu Lizardman Assassin":         nil,
		"Follower of Flouros":             nil,
		"Gigant Officer":                  nil,
		"Gorr":                            nil,
		"Granitick Duerga":                nil,
		"Guardian Basilisk":               nil,
		"Hatu Onyx Beast":                 nil,
		"Hillas":                          nil,
		"Krudel Lizardman":                nil,
		"Leto Lizardman Archer":           nil,
		"Leto Lizardman Sniper":           nil,
		"Lith Overlord":                   nil,
		"Marsh Stakato Queen":             nil,
		"Ol Mahum Betrayer":               nil,
		"Papion":                          nil,
		"Road Collector":                  nil,
		"Seer Flouros":                    nil,
		"Shyslassys":                      nil,
		"Spirit of Fire":                  nil,
		"Tasaba Lizardman":                nil,
		"Tyrant Kingpin":                  nil,
		"Actea Of Verdant Wilds":          nil,
		"Bandit Inspector":                nil,
		"Cave Ant":                        nil,
		"Dailaon":                         nil,
		"Delu Chief Kalkis":               nil,
		"Evil Eye Lord":                   nil,
		"Grave Monk":                      nil,
		"Guard Ant":                       nil,
		"Leto Lizardman Assassin":         nil,
		"Leto Lizardman Soldier":          nil,
		"Luell Of Zephyr Winds":           nil,
		"Makum Bugbear Thug":              nil,
		"Noble Ant":                       nil,
		"Pashika Son Of Voltar":           nil,
		"Road Scavenger":                  nil,
		"Stenoa Gorgon Queen":             nil,
		"Tasaba Lizardman Shaman":         nil,
		"Vault Monk":                      nil,
		"Vultus Son Of Voltar":            nil,
		"Wasp Leader":                     nil,
		"Catacomb Stakato Soldier":        nil,
		"Cave Ant Soldier":                nil,
		"Crokian Warrior":                 nil,
		"Fallen Angel":                    nil,
		"Fettered Soul":                   nil,
		"Frozen Wasteland Werewolf":       nil,
		"Hatu Crimson Bear":               nil,
		"Iron Golem":                      nil,
		"Lageos":                          nil,
		"Leto Lizardman Leader":           nil,
		"Leto Lizardman Warrior":          nil,
		"Nameless Revenant":               nil,
		"Noble Ant Leader":                nil,
		"Ogre":                            nil,
		"Ol Mahum Inspector":              nil,
		"Pako The Cat":                    nil,
		"Queen Ant Larva":                 nil,
		"Unicorn Racer":                   nil,
		"Black Willow Lurker":             nil,
		"Cave Noble Ant":                  nil,
		"Farhite":                         nil,
		"Gargos":                          nil,
		"Gigant Raider":                   nil,
		"Kinsus":                          nil,
		"Leto Lizardman Shaman":           nil,
		"Leto Lizardman Wizard":           nil,
		"Lienrik":                         nil,
		"Lith Patrolman":                  nil,
		"Mimi The Cat":                    nil,
		"Pursuer":                         nil,
		"Ragna Orc Overlord":              nil,
		"Ragna Orc Seer":                  nil,
		"Revenant of Tantos Chief":        nil,
		"Royal Guard Ant":                 nil,
		"Shadow Turen":                    nil,
		"Skeletal Mercenary":              nil,
		"Tasaba Lizardman Sniper":         nil,
		"Trimden Lord":                    nil,
		"Windsus":                         nil,
		"Alligator":                       nil,
		"Aruraune":                        nil,
		"Bandit Captain":                  nil,
		"Barrow Overlord":                 nil,
		"Bejewelled Alligator":            nil,
		"Bluebacked Alligator":            nil,
		"Crimson Lady":                    nil,
		"Dark Corpse":                     nil,
		"Death Doll":                      nil,
		"Divine Emissary":                 nil,
		"Giant Fungus":                    nil,
		"Gluttonous Kanabion":             nil,
		"Grandis":                         nil,
		"Grave":                           nil,
		"Grave Keeper Dark Horror":        nil,
		"Hatu Windsus":                    nil,
		"Hungry Spirit":                   nil,
		"Julie the Ripper":                nil,
		"Karul Bugbear":                   nil,
		"Leto Lizardman Lord":             nil,
		"Leto Lizardman Overlord":         nil,
		"Leto Shaman Ketz":                nil,
		"Lienrik Lad":                     nil,
		"Lord of the Plains":              nil,
		"Manashen Gargoyle":               nil,
		"Nos":                             nil,
		"Overlord of the Holy Lands":      nil,
		"Porta":                           nil,
		"Ragna Orc":                       nil,
		"Serpent Slave":                   nil,
		"Silhouette Tilfo":                nil,
		"Succubus Of Seduction":           nil,
		"Taik Orc":                        nil,
		"Tanor Silenos":                   nil,
		"Timak Orc":                       nil,
		"Unicorn Phantasm":                nil,
		"Vagabond of the Ruins":           nil,
		"Zenta Lizardman":                 nil,
		"Blade Stakato":                   nil,
		"Crokian Lad":                     nil,
		"Enchanted Monstereye":            nil,
		"Excuro":                          nil,
		"Giant Monstereye":                nil,
		"Leto Chief Narak":                nil,
		"Light Worm":                      nil,
		"Serpent Demon Kadesh":            nil,
		"Taik Orc Archer":                 nil,
		"Tamlin Orc":                      nil,
		"Timak Orc Archer":                nil,
		"Timak Orc Troop Archer":          nil,
		"Zenta Lizardman Scout":           nil,
		"Adiantum":                        nil,
		"Barrow Priest":                   nil,
		"Blade Stakato Worker":            nil,
		"Catherok":                        nil,
		"Dailaon Lad":                     nil,
		"Dark Spider":                     nil,
		"Dire Wyrm":                       nil,
		"Drevanil Prince Zeruel":          nil,
		"Enchanted Stone Golem":           nil,
		"Ghost Fire":                      nil,
		"Gigant Confessor":                nil,
		"Great White Shark":               nil,
		"Hallowed Priest":                 nil,
		"Lith Shaman":                     nil,
		"Mardian":                         nil,
		"Mordeo":                          nil,
		"Ragna Orc Shaman":                nil,
		"Taik Orc Warrior":                nil,
		"Tamlin Orc Archer":               nil,
		"Timak Orc Soldier":               nil,
		"Windsus Aleph":                   nil,
		"Zenta Lizardman Warrior":         nil,
		"Black Legion Stormtrooper":       nil,
		"Blade Otis":                      nil,
		"Blade Stakato Warrior":           nil,
		"Catacomb Gargoyle":               nil,
		"Crokian Lad Warrior":             nil,
		"Enchanted Iron Golem":            nil,
		"Follower of Otis":                nil,
		"Gok Magok":                       nil,
		"Karul Chief Orooto":              nil,
		"Kronbe Spider":                   nil,
		"Minotaur":                        nil,
		"Ragna Orc Archer":                nil,
		"Ricenseo":                        nil,
		"Rotting tree":                    nil,
		"Snipe Cohort":                    nil,
		"Taik Orc Shaman":                 nil,
		"Timak Orc Troop Warrior":         nil,
		"Timak Orc Warrior":               nil,
		"Timak Raider Kaikee":             nil,
		"Zaken's Elite Pikeman":           nil,
		"Zaken's Pikeman":                 nil,
		"Zenta Lizardman Shaman":          nil,
		"Blade Stakato Drone":             nil,
		"Catacomb Liviona":                nil,
		"Enchanted Gargoyle":              nil,
		"Farhite Lad":                     nil,
		"Guardian of the Ghost Town":      nil,
		"Krator":                          nil,
		"Pirate Zombie":                   nil,
		"Ragna Orc Warrior":               nil,
		"Rakin":                           nil,
		"Rotting Golem":                   nil,
		"Shindebarn":                      nil,
		"Singing Flower Darkling":         nil,
		"Singing Flower Nightmare":        nil,
		"Singing Flower Phantasm":         nil,
		"Snipe":                           nil,
		"Taik Orc Captain":                nil,
		"Timak Orc Shaman":                nil,
		"Timak Orc Troop Shaman":          nil,
		"Zaken's Archer":                  nil,
		"Zaken's Elite Archer":            nil,
		"Zenta Lizardman Matriarch":       nil,
		"Ancient Experiment":              nil,
		"Bloody Bat":                      nil,
		"Callous Kanabion":                nil,
		"Carinkain":                       nil,
		"Cruma Border":                    nil,
		"Fline":                           nil,
		"Formor":                          nil,
		"Gigant Commander":                nil,
		"Grave Overlord":                  nil,
		"Grave Wanderer":                  nil,
		"Kertang's Messenger":             nil,
		"Lith Commander":                  nil,
		"Nos Lad":                         nil,
		"Partisan Archer":                 nil,
		"Partisan Soldier":                nil,
		"Partisan Sorcerer":               nil,
		"Premo":                           nil,
		"Ragna Orc Healer":                nil,
		"Ragna Orc Mage":                  nil,
		"Shackle":                         nil,
		"Swamp Tribe":                     nil,
		"Taik Overlord Kakran":            nil,
		"Tainted Ogre":                    nil,
		"Timak Orc Overlord":              nil,
		"Timak Orc Troop Leader":          nil,
		"Trisalim Spider":                 nil,
		"Vanor Silenos":                   nil,
		"Vault Overlord":                  nil,
		"Water Giant":                     nil,
		"Weird Drake":                     nil,
		"Zaken's High Grade Watchman":     nil,
		"Zaken's Seer":                    nil,
		"Zaken's Watchman":                nil,
		"Archer of Greed":                 nil,
		"Brave Martim":                    nil,
		"Cave Servant":                    nil,
		"Decayed Ancient Pikeman":         nil,
		"Forest of Mirrors Ghost":         nil,
		"Formor Elder":                    nil,
		"Liele":                           nil,
		"Light Bringer":                   nil,
		"Probe Golem Prodigy IV":          nil,
		"Queen Undine Lad":                nil,
		"Timak Overlord Okun":             nil,
		"Trisalim Tarantula":              nil,
		"Unpleasant Humming":              nil,
		"Unpleasant Shout":                nil,
		"Validus":                         nil,
		"Vanor Silenos Grunt":             nil,
		"Varangka's Dre Vanil":            nil,
		"Weird Bunei":                     nil,
		"Wendy's Guardian":                nil,
		"Cave Servant Archer":             nil,
		"Death Flyer":                     nil,
		"Dicor":                           nil,
		"Eva's Seeker":                    nil,
		"Giant Wild Hog":                  nil,
		"Gigantic Flyer":                  nil,
		"Grave Priest":                    nil,
		"Hatar Ratman Thief":              nil,
		"Menacing Jackhammer Golem":       nil,
		"Nightmare Lord":                  nil,
		"Ossiud":                          nil,
		"Ragna Orc Sniper":                nil,
		"Secret Keeper Tree":              nil,
		"Spelunking Spider":               nil,
		"Spore Zombie":                    nil,
		"Tarlk Bugbear":                   nil,
		"Theeder":                         nil,
		"Valley Treant":                   nil,
		"Vanor Silenos Scout":             nil,
		"Vault Priest":                    nil,
		"Cave Servant Warrior":            nil,
		"Dark Knight":                     nil,
		"Fiend Archer":                    nil,
		"Hatar Ratman Boss":               nil,
		"Horrifying Cannon Golem I":       nil,
		"Horrifying Cannon Golem IV":      nil,
		"Lilim Butcher":                   nil,
		"Nephilim Sentinel":               nil,
		"Perum":                           nil,
		"Pit Archer":                      nil,
		"Ragna Orc Hero":                  nil,
		"Raikel":                          nil,
		"Riba":                            nil,
		"Satyr":                           nil,
		"Tarlk Bugbear Warrior":           nil,
		"Tarlk Raider Athu":               nil,
		"Tarlk Raider Kalath":             nil,
		"Tarlk Raider Lanka":              nil,
		"Tarlk Raider Motura":             nil,
		"Tarlk Raider Triska":             nil,
		"Theeder Piker":                   nil,
		"Vanor Silenos Warrior":           nil,
		"Cave Servant Captain":            nil,
		"Cruel Vice Golem":                nil,
		"Decayed Ancient Soldier":         nil,
		"Dragon Bearer Chief":             nil,
		"Greater Musveren":                nil,
		"Hatar Hanishee":                  nil,
		"Liangma":                         nil,
		"Mirror":                          nil,
		"Musveren":                        nil,
		"Probe Golem Champion I":          nil,
		"Ragna Orc Commander":             nil,
		"Raikel Leos":                     nil,
		"Riba Iren":                       nil,
		"Susceptor":                       nil,
		"Susceptor Prime":                 nil,
		"Tarlk Bugbear High Warrior":      nil,
		"Theeder Mage":                    nil,
		"Torfe":                           nil,
		"Unicorn":                         nil,
		"Vanor Silenos Shaman":            nil,
		"Varangka's Succubus":             nil,
		"Aracna":                          nil,
		"Betrayer Orc Hero":               nil,
		"Box Of Athrea 1":                 nil,
		"Box Of Athrea 2":                 nil,
		"Box Of Athrea 3":                 nil,
		"Box Of Athrea 4":                 nil,
		"Box Of Athrea 5":                 nil,
		"Cruma Phantom":                   nil,
		"Crypt Archon":                    nil,
		"Dark Lord":                       nil,
		"Death Knight":                    nil,
		"Decayed Ancient Knight":          nil,
		"Demon King":                      nil,
		"Deprive":                         nil,
		"Doll Master":                     nil,
		"Forest Runner":                   nil,
		"Garden Guard Leader":             nil,
		"Golden Stag Lord":                nil,
		"Grima":                           nil,
		"Harit Lizardman":                 nil,
		"Headless Knight":                 nil,
		"Mutated Elpy":                    nil,
		"Ol Mahum Transcender":            nil,
		"Partisan Court Guard":            nil,
		"Partisan Healer":                 nil,
		"Queen Undine":                    nil,
		"Ragna Orc Sorcerer":              nil,
		"Savage Kanabion":                 nil,
		"Sepulcher Archon":                nil,
		"Soul of Tree Guardian":           nil,
		"Spelunking Ant":                  nil,
		"Spiteful Ghost of Ruins":         nil,
		"Tairim":                          nil,
		"Tanor Silenos Chieftain":         nil,
		"Tarlk Basilisk":                  nil,
		"Vanor Silenos Chieftain":         nil,
		"Zaken's Elite Guard":             nil,
		"Zaken's Guard":                   nil,
		"Zaken's Royal Guard":             nil,
		"Bloodthirsty Ginzu Golem VII":    nil,
		"Elder Tarlk Basilisk":            nil,
		"Fline Elder":                     nil,
		"Harit Lizardman Grunt":           nil,
		"Horrifying Cannon Golem III":     nil,
		"Horrifying Excavator Golem III":  nil,
		"Kaim Vanil":                      nil,
		"Kaim Vanil Lad":                  nil,
		"Lilim Assassin":                  nil,
		"Lilim Great Magus":               nil,
		"Lilim Guard Knight":              nil,
		"Lilim Knight":                    nil,
		"Lilim Magus":                     nil,
		"Lilim Seer":                      nil,
		"Lilim Slave Knight":              nil,
		"Lilim Stabber":                   nil,
		"Nephilim Priest":                 nil,
		"Power of Seal Isolation":         nil,
		"Royal Cave Servant":              nil,
		"Shilen's Evil Thoughts":          nil,
		"Soldier of Grief":                nil,
		"Taik Orc Supply":                 nil,
		"Vanor Elder Kerunos":             nil,
		"Bloodthirsty Ginzu Golem II":     nil,
		"Cruel Punisher":                  nil,
		"Crypt Inquisitor":                nil,
		"Epic Cannon Golem Adjunct":       nil,
		"Fortune Bug":                     nil,
		"Ginzu Golem Prodigy X":           nil,
		"Harit Lizardman Archer":          nil,
		"Hatar Chieftain Kubel":           nil,
		"Horrifying Cannon Golem":         nil,
		"Horrifying Jackhammer Golem":     nil,
		"Hunter Gargoyle":                 nil,
		"Liele Elder":                     nil,
		"Mimic":                           nil,
		"Pirate Zombie Captain":           nil,
		"Pirate's Zombie Captain":         nil,
		"Sepulcher Inquisitor":            nil,
		"Taik Orc Seeker":                 nil,
		"Zombie Captain's Spiritual Body": nil,
		"Crimson Doll Blader":             nil,
		"Deadly Ginzu Golem V":            nil,
		"Doll Blader":                     nil,
		"Dustwind Gargoyle":               nil,
		"Epic Cannon Golem":               nil,
		"Farcran":                         nil,
		"Follower of Abigore":             nil,
		"Harit Lizardman Warrior":         nil,
		"Horrifying Cannon Golem VI":      nil,
		"Horrifying Ginzu Golem V":        nil,
		"Jewel Guardian Mara":             nil,
		"Jewel Guardian Musfel":           nil,
		"Kaim Abigore":                    nil,
		"Oel Mahum":                       nil,
		"Purgatory Wisp":                  nil,
		"Roving Soul":                     nil,
		"Tortured Undead":                 nil,
		"Valley Treant Elder":             nil,
		"Connabi":                         nil,
		"Crimson Vale Master":             nil,
		"Deadly Ginzu Golem VIII":         nil,
		"Elder Lost Watcher":              nil,
		"Grave Guard":                     nil,
		"Harit Lizardman Shaman":          nil,
		"Horrifying Ginzu Golem VIII":     nil,
		"Lilim Knight Errant":             nil,
		"Marsh Stalker":                   nil,
		"Massive Maze Bandersnatch":       nil,
		"Nephilim Swordsman":              nil,
		"Oel Mahum Warrior":               nil,
		"Sairon":                          nil,
		"Satyr Elder":                     nil,
		"Soul of Ruins":                   nil,
		"Thunder Wyrm":                    nil,
		"Vale Master":                     nil,
		"Bloody Lord Nurka":               nil,
		"Doom Wraith":                     nil,
		"Fairy Tree of Abyss":             nil,
		"Fairy Tree of Star":              nil,
		"Fairy Tree of Twilight":          nil,
		"Fairy Tree of Wind":              nil,
		"Fallen Chieftain Vegus":          nil,
		"Fallen Orc":                      nil,
		"Halingka":                        nil,
		"Harit Lizardman Matriarch":       nil,
		"Harit Lizardman Zealot":          nil,
		"Lost Gargoyle":                   nil,
		"Malruk Succubus":                 nil,
		"Marsh Drake":                     nil,
		"Oel Mahum Witch Doctor":          nil,
		"Peerless Kanabion":               nil,
		"Spirit of Timiniel":              nil,
		"Taik Orc Supply Leader":          nil,
		"Tomb Archon":                     nil,
		"Unicorn Elder":                   nil,
		"Wretched Archer":                 nil,
		"Ancient Gargoyle":                nil,
		"Doom Scout":                      nil,
		"Follower of Montagnar":           nil,
		"Imperial Slave":                  nil,
		"Knight Montagnar":                nil,
		"Lost Gargoyle Youngling":         nil,
		"Malruk Succubus Turen":           nil,
		"Oel Mahum Champion":              nil,
		"Panthera":                        nil,
		"Pronghorn Spirit":                nil,
		"Purgatory Serpent":               nil,
		"Summer Yaganitan":                nil,
		"Yintzu":                          nil,
		"Drake":                           nil,
		"Fallen Orc Archer":               nil,
		"Grave Lich":                      nil,
		"Ice Tarantula":                   nil,
		"Lilim Marauder":                  nil,
		"Nephilim Guard":                  nil,
		"Paliote":                         nil,
		"Pobby":                           nil,
		"Pronghorn":                       nil,
		"Tomb Inquisitor":                 nil,
		"Cave Keeper":                     nil,
		"Deadman's Grudge":                nil,
		"Dismal Pole":                     nil,
		"Fallen Orc Shaman":               nil,
		"Freya's Dog":                     nil,
		"Freya's Gardener":                nil,
		"Freya's Servant":                 nil,
		"Frost Tarantula":                 nil,
		"Hamrut":                          nil,
		"Hell Keeper Medusa":              nil,
		"Jewel Guardian Pyton":            nil,
		"Cave Maiden":                     nil,
		"Frost Iron Golem":                nil,
		"Grave Predator":                  nil,
		"Kranrot":                         nil,
		"Purgatory Conjurer":              nil,
		"Sharp Talon Tiger":               nil,
		"Vale master":                     nil,
		"Abyssal Jewel 1":                 nil,
		"Abyssal Jewel 2":                 nil,
		"Abyssal Jewel 3":                 nil,
		"Angel Killer":                    nil,
		"Ark Guardian Elberoth":           nil,
		"Ark Guardian Shadowfang":         nil,
		"Banshee":                         nil,
		"Beast Lord":                      nil,
		"Blitz Wyrm":                      nil,
		"Blood Queen":                     nil,
		"Bloody Lady":                     nil,
		"Claws of Splendor":               nil,
		"Crypt Guardian":                  nil,
		"Doom Servant":                    nil,
		"Eye of Splendor":                 nil,
		"Fallen Orc Captain":              nil,
		"Gamlin":                          nil,
		"Ghost of the Tower":              nil,
		"Great Demon King":                nil,
		"Imperial Gravekeeper":            nil,
		"Innersen":                        nil,
		"Lilim Priest":                    nil,
		"Lost Buffalo":                    nil,
		"Massive Kanabion":                nil,
		"Nephilim Bishop":                 nil,
		"Oel Mahum Berserker":             nil,
		"Oel Mahum Cleric":                nil,
		"Oel Mahum Leader":                nil,
		"Oel Mahum Scout":                 nil,
		"Oel Mahum Thief":                 nil,
		"Seer of Hallate":                 nil,
		"Sepulcher Guardian":              nil,
		"Archer of Despair":               nil,
		"Atan":                            nil,
		"Begrudged Archer":                nil,
		"Blade of Splendor":               nil,
		"Cave Beast":                      nil,
		"Crimson Drake":                   nil,
		"Doom Guard":                      nil,
		"Flash of Splendor":               nil,
		"Frost Buffalo":                   nil,
		"Ghastly Warrior":                 nil,
		"Hikoro":                          nil,
		"Kams":                            nil,
		"Leogul":                          nil,
		"Lesser Giant":                    nil,
		"Purgatory Shadow":                nil,
		"Blader of Despair":               nil,
		"Crendion":                        nil,
		"Crypt Sage":                      nil,
		"Death Wave":                      nil,
		"Disciple of Pilgrim":             nil,
		"Doom Archer":                     nil,
		"Kadios":                          nil,
		"Lesser Giant Soldier":            nil,
		"Lost Yeti":                       nil,
		"Page of Pilgrim":                 nil,
		"Sepulcher Sage":                  nil,
		"Ursus":                           nil,
		"Wisdom of Splendor":              nil,
		"Anger of Splendor":               nil,
		"Corpse of Deadman":               nil,
		"Corrupted Knight":                nil,
		"Doom Trooper":                    nil,
		"Follower of Storace":             nil,
		"Frost Yeti":                      nil,
		"Hallate's Royal Guard":           nil,
		"Hound Dog of Hallate":            nil,
		"Lesser Giant Scout":              nil,
		"Lesser Giant Shooter":            nil,
		"Malruk Soldier":                  nil,
		"Nephilim Centurion":              nil,
		"Pilgrim of Splendor":             nil,
		"Raider of Pastureland":           nil,
		"Resurrected Knight":              nil,
		"Slaughter Bathin":                nil,
		"Soul of Splendor":                nil,
		"Soul of Well":                    nil,
		"Trives":                          nil,
		"Venomous Storace":                nil,
		"Alkaso":                          nil,
		"Alpine Bandersnatch":             nil,
		"Barif":                           nil,
		"Corrupt Sage":                    nil,
		"Corrupted Guard":                 nil,
		"Doom Warrior":                    nil,
		"Falibati":                        nil,
		"Gerbera":                         nil,
		"Guardian Warrior of Elmoreden":   nil,
		"Hallate's Warrior":               nil,
		"Lematan's Follower":              nil,
		"Lesser Giant Mage":               nil,
		"Past Knight":                     nil,
		"Plando":                          nil,
		"Punishment of Splendor":          nil,
		"Purgatory Tarantula":             nil,
		"Victory of Splendor":             nil,
		"Alliance of Splendor":            nil,
		"Archer of Abyss":                 nil,
		"Bloody Axe Aide":                 nil,
		"Cave Howler":                     nil,
		"Doom Knight":                     nil,
		"Elmoradan's Lady":                nil,
		"Fervent Kanabion":                nil,
		"Grave Keymaster":                 nil,
		"Hallate's Knight":                nil,
		"Heathen Warrior":                 nil,
		"Judge of Marsh":                  nil,
		"Kel Mahum":                       nil,
		"Lesser Giant Elder":              nil,
		"Shout of Splendor":               nil,
		"Slaughter Executioner":           nil,
		"Spiteful Soul Leader":            nil,
		"Tame Tiny Baby Kookaburra":       nil,
		"Tiny Baby Kookaburra":            nil,
		"Tomb Guardian":                   nil,
		"Trampled Man":                    nil,
		"Triol's Pawn":                    nil,
		"Bone Maker":                      nil,
		"Bone Shaper":                     nil,
		"Bone Snatcher":                   nil,
		"Crown of Splendor":               nil,
		"Erin Ediunce":                    nil,
		"Follower of Bilette":             nil,
		"Follower of Tamuze":              nil,
		"Hallate's Maid":                  nil,
		"Heathen Executed":                nil,
		"Judge of Fire":                   nil,
		"Judge of Light":                  nil,
		"Kel Bilette":                     nil,
		"Kel Mahum Warrior":               nil,
		"Malruk Knight":                   nil,
		"Nephilim Scout":                  nil,
		"Resurrected Guard":               nil,
		"Signet of Splendor":              nil,
		"Splinter Stakato":                nil,
		"Tulben":                          nil,
		"Warlord Tamuze":                  nil,
		"Bone Collector":                  nil,
		"Dietrich":                        nil,
		"Fang of Splendor":                nil,
		"Glow Wisp":                       nil,
		"Guillotine's Ghost":              nil,
		"Hallate's Commander":             nil,
		"Heathen Archer":                  nil,
		"Hell Keeper Crimson Doll":        nil,
		"Judge of Splendor":               nil,
		"Kanadis Follower":                nil,
		"Kel Mahum Archer":                nil,
		"Kookaburra":                      nil,
		"Lematan":                         nil,
		"Malruk Berserker":                nil,
		"Mikhail":                         nil,
		"Platinum Tribe Soldier":          nil,
		"Requiem Behemoth":                nil,
		"Sacrificed Man":                  nil,
		"Skull Collector":                 nil,
		"Splinter Stakato Worker":         nil,
		"Tame Tiny Baby Buffalo":          nil,
		"Tiny Baby Buffalo":               nil,
		"Tomb Sage":                       nil,
		"Wailing of Splendor":             nil,
		"Alpine Grendel":                  nil,
		"Antelope":                        nil,
		"Bloody Lord":                     nil,
		"Bone Animator":                   nil,
		"Bone Slayer":                     nil,
		"Canyon Antelope":                 nil,
		"Devil Bat":                       nil,
		"Frenzy Stakato Soldier":          nil,
		"Hallate's Follower Mul":          nil,
		"Hallate's Inspector":             nil,
		"Hames Orc Scout":                 nil,
		"Heathen Grunt":                   nil,
		"Kel Mahum Shaman":                nil,
		"Malruk Lord":                     nil,
		"Maruk Lord":                      nil,
		"Platinum Tribe Archer":           nil,
		"Purgatory Gargoyle":              nil,
		"Requiem Lord":                    nil,
		"Skull Animator":                  nil,
		"Splinter Stakato Soldier":        nil,
		"Atrox":                           nil,
		"Bandersnatch":                    nil,
		"Bone Sweeper":                    nil,
		"Canyon Antelope Slave":           nil,
		"Ghost of Betrayer":               nil,
		"Ghost of Rebellion Soldier":      nil,
		"Hallate's Guardian":              nil,
		"Heathen Knight":                  nil,
		"Kanadis Guide":                   nil,
		"Lilim Soldier":                   nil,
		"Limal Karinness":                 nil,
		"Marsh Predator":                  nil,
		"Nephilim Archbishop":             nil,
		"Platinum Tribe Warrior":          nil,
		"Pytan":                           nil,
		"Splinter Stakato Drone":          nil,
		"Tame Tiny Baby Cougar":           nil,
		"Tiny Baby Cougar":                nil,
		"Albatross":                       nil,
		"All Seven":                       nil,
		"Best Condition":                  nil,
		"Bizarre Cocoon":                  nil,
		"Bone Grinder":                    nil,
		"Buffalo":                         nil,
		"Canyon Bandersnatch":             nil,
		"Crypt Guard":                     nil,
		"Cyclone Thunder":                 nil,
		"Dark Guard":                      nil,
		"Dark Side of the Moon":           nil,
		"Doorman of Hell":                 nil,
		"Eva's Gift Box":                  nil,
		"Everlasting":                     nil,
		"Galaxy Express":                  nil,
		"Ghost of Guillotine":             nil,
		"Gillian's Revenant":              nil,
		"Gustav":                          nil,
		"Half Moon Love":                  nil,
		"Here I Come":                     nil,
		"Huge Footmark":                   nil,
		"Hungry Baby":                     nil,
		"Karik":                           nil,
		"Kel Mahum Champion":              nil,
		"Ketra Orc Intelligence Officer":  nil,
		"Ketra Orc Supporter":             nil,
		"Lava Wyrm":                       nil,
		"Light My Fire":                   nil,
		"Magus Valac":                     nil,
		"Malcom1":                         nil,
		"Malcom2":                         nil,
		"Malcom3":                         nil,
		"Malcom4":                         nil,
		"Malcom5":                         nil,
		"Malcom6":                         nil,
		"Malcom7":                         nil,
		"Malcom8":                         nil,
		"Messenger Angel":                 nil,
		"Nasty Green":                     nil,
		"Needle Stakato":                  nil,
		"Orpheus Resurrecter":             nil,
		"Over the top":                    nil,
		"Platinum Tribe Shaman":           nil,
		"Powder Keg":                      nil,
		"Raging Revolution":               nil,
		"Red Bullet":                      nil,
		"Red Hot":                         nil,
		"Restrainer of Glory":             nil,
		"Royal Straight":                  nil,
		"Ruptured Kanabion":               nil,
		"Salty Dog":                       nil,
		"Scarecrow":                       nil,
		"Sepulcher Guard":                 nil,
		"Shining Silver":                  nil,
		"Shooting Star":                   nil,
		"Shortcut":                        nil,
		"Sleeping Ant Larva1":             nil,
		"Sleeping Ant Larva2":             nil,
		"Sleeping Ant Larva3":             nil,
		"Sleeping Ant Larva4":             nil,
		"Sleeping Ant Larva5":             nil,
		"Sleeping Ant Larva6":             nil,
		"Typhoon Tiger":                   nil,
		"Valentine Blue":                  nil,
		"Wind Rider":                      nil,
		"Zealot of Shilen":                nil,
	}
)
